# Generated by Django 2.2.4 on 2020-11-15 14:51

from django.db import migrations


def fill_new_building_field(apps, shema_editor):
    apps.get_model('property', 'Flat').objects.filter(construction_year__gte=2015).update(new_building=True)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_field)
    ]