# Generated by Django 2.2.4 on 2020-11-15 15:07

from django.db import migrations


def fill_new_building_field(apps, shema_editor):
    apps.get_model('property', 'Flat').objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20201115_1951'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_field)
    ]
